version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ../static:/var/www/project/static
    depends_on:
      - php

  php:
    build: ./php
    container_name: php5.6-fpm
    volumes:
      - ../:/var/www/project:cached
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3356:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
